#!/bin/bash
echo "Ahora se instalara adbxploit"
sleep 2s
pip install colorama
sleep 1s
apt update > /dev/null 2>&1 && apt --assume-yes install wget > /dev/null 2>&1 && wget https://github.com/MasterDevX/Termux-ADB/raw/master/InstallTools.sh -q && bash InstallTools.sh
sleep 2s
echo "ADB ha sido instalado"
sleep 1s
clear
ls
